// Generated by website/build.js — run `npm run website` to refresh.
window.PACKS = [
  {
    "id": "azure",
    "label": "Azure",
    "frameWidth": 192,
    "frameHeight": 208,
    "columns": 8,
    "rows": 9,
    "fps": 6,
    "poses": {
      "idle": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 0,
        "frames": 6
      },
      "think": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 6,
        "frames": 6
      },
      "excited": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 3,
        "frames": 4
      },
      "stress": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 7,
        "frames": 6
      },
      "walk": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 1,
        "frames": 8
      },
      "point": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 4,
        "frames": 5
      },
      "sleep": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 5,
        "frames": 8
      },
      "cheer": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 2,
        "frames": 8
      },
      "wave": {
        "file": "img/packs/azure-spritesheet.webp",
        "row": 8,
        "frames": 6
      }
    }
  },
  {
    "id": "crumb",
    "label": "Crumb",
    "frameWidth": 192,
    "frameHeight": 208,
    "columns": 8,
    "rows": 9,
    "fps": 6,
    "poses": {
      "idle": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 0,
        "frames": 6
      },
      "think": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 6,
        "frames": 6
      },
      "excited": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 3,
        "frames": 4
      },
      "stress": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 7,
        "frames": 6
      },
      "walk": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 1,
        "frames": 8
      },
      "point": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 4,
        "frames": 5
      },
      "sleep": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 5,
        "frames": 8
      },
      "cheer": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 2,
        "frames": 8
      },
      "wave": {
        "file": "img/packs/crumb-spritesheet.webp",
        "row": 8,
        "frames": 6
      }
    }
  },
  {
    "id": "fox",
    "label": "Fox",
    "frameWidth": 192,
    "frameHeight": 208,
    "columns": 8,
    "rows": 9,
    "fps": 6,
    "poses": {
      "idle": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 0,
        "frames": 6
      },
      "think": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 6,
        "frames": 6
      },
      "excited": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 3,
        "frames": 4
      },
      "stress": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 7,
        "frames": 6
      },
      "walk": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 1,
        "frames": 8
      },
      "point": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 4,
        "frames": 5
      },
      "sleep": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 5,
        "frames": 8
      },
      "cheer": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 2,
        "frames": 8
      },
      "wave": {
        "file": "img/packs/fox-spritesheet.webp",
        "row": 8,
        "frames": 6
      }
    }
  },
  {
    "id": "foxbow",
    "label": "Foxbow",
    "frameWidth": 192,
    "frameHeight": 208,
    "columns": 8,
    "rows": 9,
    "fps": 6,
    "poses": {
      "idle": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 0,
        "frames": 6
      },
      "think": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 6,
        "frames": 6
      },
      "excited": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 3,
        "frames": 4
      },
      "stress": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 7,
        "frames": 6
      },
      "walk": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 1,
        "frames": 8
      },
      "point": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 4,
        "frames": 5
      },
      "sleep": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 5,
        "frames": 8
      },
      "cheer": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 2,
        "frames": 8
      },
      "wave": {
        "file": "img/packs/foxbow-spritesheet.webp",
        "row": 8,
        "frames": 6
      }
    }
  },
  {
    "id": "miso",
    "label": "Miso",
    "frameWidth": 192,
    "frameHeight": 208,
    "columns": 8,
    "rows": 9,
    "fps": 6,
    "poses": {
      "idle": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 0,
        "frames": 6
      },
      "think": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 6,
        "frames": 6
      },
      "excited": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 3,
        "frames": 4
      },
      "stress": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 7,
        "frames": 6
      },
      "walk": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 1,
        "frames": 8
      },
      "point": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 4,
        "frames": 5
      },
      "sleep": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 5,
        "frames": 8
      },
      "cheer": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 2,
        "frames": 8
      },
      "wave": {
        "file": "img/packs/miso-spritesheet.webp",
        "row": 8,
        "frames": 6
      }
    }
  }
];
