'use strict';

/**
 * Build the website's cast from the app's own assets — run `npm run website`.
 *
 * The landing page shows the real buddies, so it should never drift from what
 * the app actually ships: this copies the generated GIFs for the drawn cast,
 * and picks up every sprite pack currently dropped into the themes folder
 * (azure, crumb, fox… whatever is there today) with the same theme.json
 * parsing the app uses. The result is `img/buddies/`, `img/packs/` and
 * `cast-data.js`, which script.js animates in the browser.
 *
 * Downloaded packs are copied for *this machine's* copy of the site only —
 * the whole website/ folder is gitignored. Publish it and their own licences
 * apply; the drawn cast is the part that's unambiguously yours to host.
 */

const fs = require('node:fs');
const path = require('node:path');
const { customThemes, THEMES_DIR } = require('../src/characters');

const SITE = __dirname;
const BUDDIES = path.join(SITE, 'img', 'buddies');
const PACKS = path.join(SITE, 'img', 'packs');

const POSES = ['idle', 'think', 'excited', 'stress', 'walk', 'point', 'sleep', 'cheer', 'wave'];
// The hero/cast GIFs: clip is per-colour, the blue one fronts the page.
const CLIP_COLOUR = '4fa3d1';
const EXTRA_COLOURS = ['e0803a', '6cbf6c', 'c264c9', 'd4b03c'];

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

function buildDrawnCast() {
  for (const pose of POSES) {
    copy(path.join(THEMES_DIR, 'clip', `${CLIP_COLOUR}-${pose}.gif`), path.join(BUDDIES, `clip-${pose}.gif`));
    copy(path.join(THEMES_DIR, 'cat', `${pose}.gif`), path.join(BUDDIES, `cat-${pose}.gif`));
    copy(path.join(THEMES_DIR, 'clod', `${pose}.gif`), path.join(BUDDIES, `clod-${pose}.gif`));
  }
  for (const colour of EXTRA_COLOURS) {
    copy(path.join(THEMES_DIR, 'clip', `${colour}-idle.gif`), path.join(BUDDIES, `clip-${colour}-idle.gif`));
  }
}

/** Every dropped-in sprite pack, with its sheet copied and paths rewritten. */
function buildPacks() {
  const packs = [];
  for (const theme of customThemes()) {
    const files = new Map(); // renderer-relative path -> site-relative path
    const poses = {};
    for (const [name, pose] of Object.entries(theme.sheet.poses)) {
      // pose.file is 'assets/themes/<id>/<file>' relative to src/renderer.
      const abs = path.join(THEMES_DIR, '..', '..', pose.file.replace(/^assets\//, 'assets/'));
      const rel = `img/packs/${theme.id}-${path.basename(pose.file)}`;
      if (!files.has(pose.file)) {
        copy(path.join(THEMES_DIR, theme.id, path.basename(pose.file)), path.join(SITE, rel));
        files.set(pose.file, rel);
      }
      poses[name] = { file: files.get(pose.file), row: pose.row, frames: pose.frames };
      void abs;
    }
    packs.push({
      id: theme.id,
      label: theme.label,
      frameWidth: theme.sheet.frameWidth,
      frameHeight: theme.sheet.frameHeight,
      columns: theme.sheet.columns,
      rows: theme.sheet.rows,
      fps: theme.sheet.fps,
      poses,
    });
  }
  return packs;
}

function main() {
  fs.rmSync(BUDDIES, { recursive: true, force: true });
  fs.rmSync(PACKS, { recursive: true, force: true });
  buildDrawnCast();
  const packs = buildPacks();
  // A .js file rather than JSON so the page works from file:// (fetch won't).
  fs.writeFileSync(
    path.join(SITE, 'cast-data.js'),
    `// Generated by website/build.js — run \`npm run website\` to refresh.\nwindow.PACKS = ${JSON.stringify(packs, null, 2)};\n`
  );
  console.log(`website: drawn cast + ${packs.length} sprite packs → img/, cast-data.js`);
}

main();
